#!/usr/bin/env bash
# Render dist/ from ddlc-palette's base16 schemes. Run it after the palette moves and commit both
set -euo pipefail

here="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
out="$here/dist"

usage() {
  cat <<EOF
generate.sh — render the kitty and btop themes out of the base16 schemes

  --light FILE   base16-ddlc-light.yaml   (or \$DDLC_BASE16_LIGHT)
  --dark FILE    base16-ddlc-dark.yaml    (or \$DDLC_BASE16_DARK)

Both come from ddlc-palette, and nix develop puts them in the environment already.
Without Nix, take them from the palette repository:

  curl -sSLO https://raw.githubusercontent.com/rokokol/ddlc-palette/master/dist/base16-ddlc-dark.yaml
EOF
}

declare -A scheme=(
  [light]="${DDLC_BASE16_LIGHT:-}"
  [dark]="${DDLC_BASE16_DARK:-}"
)

while [[ $# -gt 0 ]]; do
  case "$1" in
    --light)
      scheme[light]="${2:?file required}"
      shift 2
      ;;
    --dark)
      scheme[dark]="${2:?file required}"
      shift 2
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      usage >&2
      exit 1
      ;;
  esac
done

# The slot tables below name base16 slots, so resolve them once per variant. $V picks the variant
declare -A slot
for variant in light dark; do
  file="${scheme[$variant]}"
  [ -n "$file" ] || {
    echo "generate.sh: no $variant scheme — pass --$variant or set DDLC_BASE16_${variant^^}" >&2
    exit 1
  }
  n=0
  while read -r key hex; do
    slot["$variant/$key"]="$hex"
    n=$((n + 1))
  done < <(sed -n 's/^  \(base[0-9A-F][0-9A-F]\): "\(#[0-9A-F]\{6\}\)".*/\1 \2/p' "$file")
  # Sixteen slots or it is not a base16 scheme, and a half-read file would render a half-theme
  [ "$n" = 16 ] || {
    echo "generate.sh: $file has $n slots, want 16" >&2
    exit 1
  }
done
s() { printf '%s' "${slot["$V/$1"]}"; }

mkdir -p "$out"
banner="Generated by generate.sh from ddlc-palette's base16 schemes — do not edit"

for V in light dark; do

  # Slot for slot the mapping tinted-theming/tinted-kitty uses, with one departure: it grounds
  # the selection in base03, which leaves base05 on it at 1.65:1 here, so base02 carries it
  {
    echo "# $banner"
    echo "# vim:ft=kitty"
    echo "# Include this from kitty.conf: include ddlc-kitty-$V.conf"
    echo
    echo "background $(s base00)"
    echo "foreground $(s base05)"
    echo "selection_background $(s base02)"
    echo "selection_foreground $(s base05)"
    echo "cursor $(s base05)"
    echo "cursor_text_color $(s base00)"
    echo "url_color $(s base04)"
    echo "active_border_color $(s base03)"
    echo "inactive_border_color $(s base01)"
    echo "wayland_titlebar_color $(s base00)"
    echo "macos_titlebar_color $(s base00)"
    echo "active_tab_background $(s base00)"
    echo "active_tab_foreground $(s base05)"
    echo "inactive_tab_background $(s base01)"
    echo "inactive_tab_foreground $(s base04)"
    echo "tab_bar_background $(s base01)"
    echo
    while read -r n slot_name; do echo "color$n $(s "$slot_name")"; done <<'ANSI'
0 base00
1 base08
2 base0B
3 base0A
4 base0D
5 base0E
6 base0C
7 base05
8 base02
9 base08
10 base0B
11 base0A
12 base0D
13 base0E
14 base0C
15 base07
16 base09
17 base0F
18 base01
19 base02
20 base04
21 base06
ANSI
  } >"$out/ddlc-kitty-$V.conf"

  # btop has no base16 template anywhere upstream, so this mapping is ours. Meters that carry no
  # scale are one colour — btop reads that as a start with an empty mid and end
  {
    echo "# $banner"
    echo "# Drop into ~/.config/btop/themes/ and select it with color_theme=\"ddlc-$V\""
    echo
    echo "theme[main_bg]=\"$(s base00)\""
    echo "theme[main_fg]=\"$(s base05)\""
    echo "theme[title]=\"$(s base06)\""
    echo "theme[hi_fg]=\"$(s base0A)\""
    echo "theme[selected_bg]=\"$(s base02)\""
    echo "theme[selected_fg]=\"$(s base06)\""
    echo "theme[inactive_fg]=\"$(s base03)\""
    echo "theme[graph_text]=\"$(s base04)\""
    echo "theme[meter_bg]=\"$(s base01)\""
    echo "theme[proc_misc]=\"$(s base0B)\""
    echo "theme[cpu_box]=\"$(s base0D)\""
    echo "theme[mem_box]=\"$(s base0B)\""
    echo "theme[net_box]=\"$(s base0E)\""
    echo "theme[proc_box]=\"$(s base0C)\""
    echo "theme[div_line]=\"$(s base03)\""
    # Load rises through the palette's warm accents: green, then yellow, then red
    for gradient in temp cpu process; do
      echo "theme[${gradient}_start]=\"$(s base0B)\""
      echo "theme[${gradient}_mid]=\"$(s base0A)\""
      echo "theme[${gradient}_end]=\"$(s base08)\""
    done
    while read -r meter slot_name; do
      echo "theme[${meter}_start]=\"$(s "$slot_name")\""
      echo "theme[${meter}_mid]=\"\""
      echo "theme[${meter}_end]=\"\""
    done <<'METERS'
free base0B
cached base0C
available base0A
used base08
download base0D
upload base0E
METERS
  } >"$out/ddlc-btop-$V.theme"

done

echo "wrote, per variant, $out/{ddlc-kitty-VARIANT.conf,ddlc-btop-VARIANT.theme}"
